# Generated by Django 3.2.18 on 2023-02-22 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanage_app', '0002_department_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='basicpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basicpay', models.CharField(max_length=50)),
                ('DESIGNATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffmanage_app.department')),
            ],
        ),
    ]
