# Generated by Django 3.2.18 on 2023-02-22 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanage_app', '0003_basicpay'),
    ]

    operations = [
        migrations.CreateModel(
            name='deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_type', models.CharField(max_length=50)),
                ('salary_limit', models.CharField(max_length=50)),
                ('percentage', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='basicpay',
            name='DESIGNATION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffmanage_app.designation'),
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('experiance', models.CharField(max_length=50)),
                ('father', models.CharField(max_length=50)),
                ('mother', models.CharField(max_length=50)),
                ('joindate', models.CharField(max_length=50)),
                ('acctno', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=50)),
                ('recipient_name', models.CharField(max_length=50)),
                ('photo', models.FileField(max_length=50, upload_to='')),
                ('status', models.CharField(max_length=50)),
                ('DESIGNATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffmanage_app.designation')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffmanage_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('DEPARTMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffmanage_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='assignwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('DESIGNATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffmanage_app.designation')),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffmanage_app.staff')),
            ],
        ),
    ]
