# Generated by Django 3.2.18 on 2023-03-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanage_app', '0005_allnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignwork',
            name='DESIGNATION',
        ),
        migrations.AddField(
            model_name='assignwork',
            name='work',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
