# Generated by Django 3.2.18 on 2023-03-10 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanage_app', '0006_auto_20230303_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('allowance_type', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffmanage_app.staff')),
            ],
        ),
    ]
