# Generated by Django 3.2.18 on 2023-03-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanage_app', '0007_allowance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='joindate',
            field=models.DateField(max_length=50),
        ),
    ]
