# Generated by Django 3.2.18 on 2023-03-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanage_app', '0008_alter_staff_joindate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='date',
            field=models.DateField(max_length=50),
        ),
    ]
