# Generated by Django 3.2.18 on 2023-03-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanage_app', '0009_alter_allowance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.CharField(max_length=200),
        ),
    ]
