# Generated by Django 3.2.18 on 2023-03-24 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanage_app', '0010_alter_staff_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('entry_time', models.CharField(max_length=50)),
                ('exit_time', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffmanage_app.staff')),
            ],
        ),
    ]
