# Generated by Django 3.2.18 on 2023-04-06 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanage_app', '0012_auto_20230331_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('from_date', models.CharField(max_length=50)),
                ('to_date', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=50)),
                ('no_leaves', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffmanage_app.staff')),
            ],
        ),
    ]
