# Generated by Django 3.2.18 on 2023-04-14 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanage_app', '0015_resignation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resignation',
            name='to_date',
        ),
    ]
