# Generated by Django 3.2.18 on 2023-04-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanage_app', '0016_remove_resignation_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='allnotification',
            name='leave_date',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
