# Generated by Django 3.2.18 on 2023-04-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanage_app', '0017_allnotification_leave_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wokingdays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('leave_date', models.CharField(default=0, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='allnotification',
            name='leave_date',
        ),
    ]
