# Generated by Django 3.2.18 on 2023-04-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanage_app', '0018_auto_20230427_1740'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wokingdays',
            new_name='workingdays',
        ),
    ]
