# Generated by Django 3.2.18 on 2023-04-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanage_app', '0020_alter_workingdays_leave_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='from_date',
            field=models.DateField(default='2023-04-29', max_length=50),
        ),
        migrations.AlterField(
            model_name='leave',
            name='to_date',
            field=models.DateField(default='2023-04-29', max_length=50),
        ),
    ]
